### ISSUE TITLE
Portraits for regular Motherbase staff members?

### ISSUE THREAD

**Issue by Fironet** [unknown321/mgswaifus#1]
Was wondering if there's a location for all the staff portraits (and their variants) seen in the Motherbase iDroid list, since they cover the full range of available faces and appear to be static, base images which then have processing applied in-game to fit the context (iDroid, volunteer screen).

**Comment by unknown321** [comment]
First of all, I would like to note that this issue is not an issue - just a question. If you want to ask questions, please ask them on xentax - http://forum.xentax.com/viewtopic.php?f=10&t=12407 or in mgsvmodding discord - https://discord.gg/6kf9cJZ

Second, staff portraits are in /Assets/tpp/ui/texture/StaffImage/. Not sure in which .dat file, maybe in 01.dat. Just unpack everything.

**Comment by Fironet** [comment]
Thanks for the tip. Related as you noted the web page list it was incomplete picture-wise and was looking for more staff portraits/locations to be added, which I was also after since I'd manually taken screenshots of every female staff portrait face type in-game and was going through the male ones, too. Apologies if it seemed the wrong place to ask.
